module.exports = function () { 
	return {
		WORD_HINT_PERCENT: .60,
		CHECK_QUEUE_INTERVAL: 300,
		PHRASE_DURATION: 45 * 1000,
		PHRASE_LIMIT: 3,
		MAX_GAME_SIZE: 7,
		STAGE_PLAYER_SCORE_MOD: 2,
		WINNING_SCORE: 20,
		TIME_BETWEEN_GAMES: 15 * 1000,
		MONGO_DB_CONNECTION: process.env.PHRASE_MONGO_DB
	} 
};